/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RumbleTest */

#ifndef _Included_RumbleTest
#define _Included_RumbleTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RumbleTest
 * Method:    rumble
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_RumbleTest_rumble
  (JNIEnv *, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif

