/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Rumbler */

#ifndef _Included_Rumbler
#define _Included_Rumbler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Rumbler
 * Method:    rumble
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_Rumbler_rumble
  (JNIEnv *, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
